# -*- coding: utf-8 -*-
"""#2 A* on the Sudoku Cube.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ic4ApSRhwGbk4Cfe4rkxjD4dU1LnsN-n
"""

import random
from math import ceil

State = tuple

def startingConfig() -> State:
    """Custom start state """
    # Each face is row-major
    F = (9, 5, 2,
         3, 8, 1,
         6, 7, 4)
    U = (8, 1, 3,
         4, 6, 7,
         2, 9, 5)
    D = (1, 2, 8,
         5, 3, 9,
         7, 4, 6)
    L = (7, 1, 8,
         2, 4, 6,
         9, 3, 5)
    R = (4, 6, 3,
         7, 5, 9,
         1, 2, 8)
    B = (9, 5, 2,
         3, 8, 1,
         6, 7, 4)
    return F + U + D + L + R + B

# Rotate face clockwise function
def rotateClockData(face_data: tuple) -> tuple:
  row1 = face_data[0:3]
  row2 = face_data[3:6]
  row3 = face_data[6:9]
  newFace = (row3[0], row2[0], row1[0],
             row3[1], row2[1], row1[1],
             row3[2], row2[2], row1[2])
  return newFace

# Rotate face counter-clockwise function by rotating clockwise three times
def rotateCounterData(face_data: tuple) -> tuple:
  current = rotateClockData(face_data)
  current = rotateClockData(current)
  return rotateClockData(current)

# Return which adjacent edges will need to be changed and which row/column is changed
# Formatted adj1 -> adj2 -> adj3 -> adj4 in clockwise fashion
def adjacentEdges(face_name: str) -> list[tuple[str, list[int], str, list[int]]]:
  if face_name == 'F':
    return [('U',[6,7,8], 'R',[0,3,6]),
    ('R',[6,3,0], 'D',[0,1,2]),               # reverse cycle (1st column must be reversed; we are iterating left-right, top-bottom)
    ('D',[0,1,2], 'L',[2,5,8]),
    ('L',[8,5,2], 'U',[6,7,8])]               # reverse cycle
  elif face_name == 'U':
    return [('F',[0,1,2], 'L',[0,1,2]),
    ('L',[0,1,2], 'B',[0,1,2]),
    ('B',[0,1,2], 'R',[0,1,2]),
    ('R',[0,1,2], 'F',[0,1,2])]
  elif face_name == 'D':
    return [('F',[6,7,8], 'R',[6,7,8]),
    ('R',[6,7,8], 'B',[6,7,8]),
    ('B',[6,7,8], 'L',[6,7,8]),
    ('L',[6,7,8], 'F',[6,7,8])]
  elif face_name == 'L':
    return [('F',[0,3,6], 'D',[0,3,6]),
    ('D',[6,3,0], 'B',[2,5,8]),           # reverse cycle
    ('B',[8,5,2], 'U',[0,3,6]),           # reverse cycle
    ('U',[0,3,6], 'F',[0,3,6])]
  elif face_name == 'R':
    return [('F',[2,5,8], 'U',[2,5,8]),
    ('U',[8,5,2], 'B',[0,3,6]),           # reverse cycle
    ('B',[6,3,0], 'D',[2,5,8]),           # reverse cycle
    ('D',[2,5,8], 'F',[2,5,8])]
  elif face_name == 'B':
    return [('U',[0,1,2], 'L',[0,3,6]),
    ('L',[0,3,6], 'D',[8,7,6]),           # reverse cycle
    ('D',[8,7,6], 'R',[2,5,8]),           # reverse cycle
    ('R',[2,5,8], 'U',[0,1,2])]

def rotateClock(state: State, face_name: str) -> State:
  newFace = rotateClockData(getFace(face_name, state))      # returns a rotated tuple
  newState = setFace(face_name, newFace, state)              # returns the new state
  adjacent = adjacentEdges(face_name)                       # returns a list of tuples (with face name)


# i indicates which face (taken from adjacentEdges)
  for face, positions, face2, positions2 in adjacent:
    original = getFace(face, state)                         # get our current tuple
    values = [original[i] for i in positions]
    newValues = list(getFace(face2, newState))              # variable for list of empty tuple
  # populate our new empty tuple with values from adjacentEdges
    for j, pos in enumerate(positions2):
      newValues[pos] = values[j]
    newState = setFace(face2, tuple(newValues), newState) # finalize rotation
  return newState

def rotateCounterClock(state: State, face_name: str) -> State:
  newState = rotateClock(state, face_name)
  newState = rotateClock(newState, face_name)
  newState = rotateClock(newState, face_name)
  return newState

# randomizer
# we are choosing a random face to rotate and then we randomly decide to rotate C or CCW
# ADD A CHECK THAT NEXT MOVE DOES UNDO THE PREVIOUS MOVE
def randomizer(state:State,numMoves:int) ->  tuple[State, list[tuple[str, int]]]:
  moves = ['F','U','D','L','R','B']
  rotation = [0,1]  # 0: clockwise 1: counterClockwise
  listOfMoves = []
  last_face = None
  last_dir = None
  for i in range(numMoves):
    while True:
      face = random.choice(moves)
      direction = random.choice(rotation)
      if not (last_face == face and last_dir is not None and direction != last_dir):
        break

    listOfMoves.append((face,direction))
    if direction  == 1:
      state = rotateCounterClock(state,face)
    else:
      state = rotateClock(state,face)
    last_face = face
    last_dir = direction
  return state, listOfMoves

# sanity check (reverse Randomizer)
def reverseRandomizer(state:State, listOfMoves:list) -> State:
  for move in reversed(listOfMoves):
    if move[1] == 1:
      state = rotateClock(state,move[0])
    else:
      state = rotateCounterClock(state,move[0])
  return state

# Returns face
def getFace(face_name: str, state: State) -> tuple:
  if face_name == 'F':
    return state[0:9]
  elif face_name == 'U':
    return state[9:18]
  elif face_name == 'D':
    return state[18:27]
  elif face_name == 'L':
    return state[27:36]
  elif face_name == 'R':
    return state[36:45]
  elif face_name == 'B':
    return state[45:54]

# Returns changed face
def setFace(face_name: str, face_data: tuple, state: State) -> State:
  if face_name == 'F':
    return face_data + state[9:54]
  elif face_name == 'U':
    return state[0:9] + face_data + state[18:54]
  elif face_name == 'D':
    return state[0:18] + face_data + state[27:54]
  elif face_name == 'L':
    return state[0:27] + face_data + state[36:54]
  elif face_name == 'R':
    return state[0:36] + face_data + state[45:54]
  elif face_name == 'B':
    return state[0:45] + face_data

def displayGUI(state: State):
  F = getFace('F', state)
  U = getFace('U', state)
  D = getFace('D', state)
  L = getFace('L', state)
  R = getFace('R', state)
  B = getFace('B', state)


  print("\n          UP Face")
  for i in range(3):
      print(f"          {U[i*3]} {U[i*3+1]} {U[i*3+2]}")

  print("\n  LEFT   FRONT  RIGHT   BACK")
  for i in range(3):  # For each row
      print(f"  {L[i*3]} {L[i*3+1]} {L[i*3+2]}   {F[i*3]} {F[i*3+1]} {F[i*3+2]}   {R[i*3]} {R[i*3+1]} {R[i*3+2]}   {B[i*3]} {B[i*3+1]} {B[i*3+2]}")

  # Print DOWN face
  print("\n          DOWN Face")
  for i in range(3):
      print(f"          {D[i*3]} {D[i*3+1]} {D[i*3+2]}")

  print()

# sanity check
def test_four_turns():
  for f in ['F', 'U', 'D', 'L', 'R', 'B']:
    s = startingConfig()
    for i in range(4):
      s = rotateClock(s, f)
    assert s == startingConfig(), "failed"
  print("Pass)")

ADJ = {
  'U': ['F','R','B','L'],
  'D': ['F','L','B','R'],
  'F': ['U','R','D','L'],
  'B': ['U','L','D','R'],
  'L': ['U','F','D','B'],
  'R': ['U','B','D','F'],
}

def heuristic(state: State) -> int:
  # constants to help heuristic definition
  faceOrder = ['F','U','D','L','R','B']

  # duplicate checking heuristic function
  faceDupes = []
  countsByFace = {}
  for face in faceOrder:              # for each face count number of distinct digits
    faceData = getFace(face, state)
    distinct = [0] * 10               # list to keep track of digits 1-9 (index 1 maps to 1 in this case)
    for value in faceData:    # Iterate through indices instead of values
      distinct[value] +=1
    countsByFace[face] = distinct
    dupe = 0
    for digit in range(1,10):          # traverse distinct to count # of duplicates
      if distinct[digit] > 1:
        dupe += distinct[digit] - 1
    faceDupes.append(dupe)
# divide global by 12 (no. of stickers changed)
  hglobalMax = ceil(sum(faceDupes)/12)      # heuristic value for duplicates

  distancetoSurplus = 0
  for d in range (1,10):# digit index
    surplus = [i for i in faceOrder if countsByFace[i][d]>1] # Face of the surplus digit d
    deficit = [i for i in faceOrder if countsByFace[i][d]<1] # Face of the deficit digit d
    deficitDistance = len(deficit)
    notAdjacent = sum(1 for f in deficit if not any(num in surplus for num in ADJ[f] ))
    distancetoSurplus += (deficitDistance + notAdjacent)
  hAdjmoves = ceil(distancetoSurplus/12)  # each move can move 12 stickers between faces

  return max(hglobalMax,hAdjmoves)

def sanityCheck():

    displayGUI(startingConfig())  # This prints solved state
    newFace, _ = randomizer(startingConfig(), 10) # randomizes ten moves (2nd parameter)
    displayGUI(newFace) # displays the randomized cube
    print(heuristic(newFace))

    # Testing Full Heurisitc Functionality When Random moves
    testRan = [1, 2, 5, 10, 20]
    for i in testRan:
        randomized_state, _ = randomizer(startingConfig(), i)
        print(f"Heuristic for {i} moves: {heuristic(randomized_state)}")

    # Test heuristic with multiple random trials. New Sanity Check
    testRan = [0,1, 2 ,5, 10, 20]
    num_trials = 100 # Number of random trials for each move count

    for num_moves in testRan:
        max_heuristic = 0
        for _ in range(num_trials):
            randomized_state, _ = randomizer(startingConfig(), num_moves)
            h = heuristic(randomized_state)
            if h > max_heuristic:
                max_heuristic = h
    print(f"Maximum heuristic for {num_moves} moves over {num_trials} trials: {max_heuristic}")

def CWRandomizer(state:State,numMoves:int) ->  tuple[State, list[tuple[str, int]]]: # Randomizes only clockwise per Hint. Making A* easier to solve
  moves = ['F','U','D','L','R','B']
  sequenceOfMoves = []
  last = None
  for i in range(numMoves):  # Does not need Check for Last move since CCW is impossible for next move
    face = random.choice(moves)
    if last is not None and face == last:
      face = random.choice([m for m in moves if m != last])
    state = rotateClock(state,face)
    sequenceOfMoves.append((face,0))
    last = face
  return state, sequenceOfMoves

def tupleToBytes(state: State) -> bytes:
  ouput = bytearray(27) # mutable seques of bytes
  for i in range(27): #27 since 2 stickers stored in one byte
    evenInt = state[2*i] & 0x0F
    oddInt = state[2*i+1] & 0x0F
    ouput[i] = (evenInt << 4) | oddInt
  return bytes(ouput)   # returns even digit then odd digit in order

def bytesToTuple (bytesX: bytes) -> State:
  state = []
  for byte in bytesX:
    state.append((byte >> 4) & 0x0F)  #shifts to grab first sticker
    state.append(byte & 0x0F)    # grabs second
  return tuple(state)

from collections import OrderedDict
class HeuristicLRU:
  def __init__(self, max_size: int = 1000000):
    self.max_size = max_size
    self.store = OrderedDict() # keep track elements inserted in cache
    self.hits = 0 # how many times accessed
    self.misses = 0 # how many times not accessed
  def get(self, key):
    try: # try except since Key error is apart OrderedDict
      value = self.store.pop(key)  #removes the key
      self.store[key] = value # Mark it at end / MRU(Most-Recently-Used)
      self.hits += 1
      return value
    except KeyError:
      self.misses += 1
      return None
  def put(self, key, value):
    if key in self.store: # if in cache
      self.store.pop(key) # removes key
    elif len(self.store) >= self.max_size: # if cahce is at max
      self.store.popitem(last=False) # evict the LRU
    self.store[key] = value # add key as MRU

  def reSize(self, new_size: int):
    while len(self.store) > new_size:
      self.store.popitem(last=False) # continuously evicts LRU elements untill new size

MAINCACHE = HeuristicLRU(1000000)
def HeuristicByCache(compTuple:bytes ) ->int:
  value = MAINCACHE.get(compTuple) # tries to get it from cache
  if value is not None:
    return value #if in cache
  hvalue = heuristic(bytesToTuple(compTuple)) # intensive computation
  MAINCACHE.put(compTuple, hvalue) # adds to cache
  return hvalue

import psutil

class ResourceMonitor:
  def __init__(self, maxMemoryUsage=0.95, minFreeMemoryMb=1024,checkEvery = 2048):
    self.maxMemoryUsage = maxMemoryUsage
    self.minFreeMemoryMb = minFreeMemoryMb
    self._checkCount = 0
    self.checkEvery = int(checkEvery)
  def shouldTerminateSearch(self) -> bool: # if too much memeory
    self._checkCount += 1
    if self._checkCount % self.checkEvery != 0:
      return False

    # Get current memory statistics
    memoryInfo = psutil.virtual_memory()

    # Calculate how much memory is currently being used
    memoryUsageFraction = (memoryInfo.total - memoryInfo.available) / memoryInfo.total
    availableMb = memoryInfo.available / (1024 * 1024)

    # stop if either is exceeded
    usageTooHigh = memoryUsageFraction >= self.maxMemoryUsage
    freeMemoryTooLow = availableMb < self.minFreeMemoryMb

    return usageTooHigh or freeMemoryTooLow

import time
import heapq

def aStarMethod(randomizedState:State , resourceMonitor:ResourceMonitor) -> dict:
  searchStartTimer = time.perf_counter()

  possibleMoves = ['F','U','D','L','R','B']

  initialH = heuristic(randomizedState)  # inital heuristic

  if(initialH == 0):
    return {'Solved' :True , 'moves': [] , 'nodesExpanded': 0 , 'finalLayerNodes' : 1 , 'searchTime' : 0.0  }

  startKey = tupleToBytes(randomizedState) # config to smaller data struct
  frontier = [(initialH,initialH,0,startKey)]  # g is 0 at start f=g+h = 0+h = h.
  # Our tie breaker is linear increasing counter; meaning first explored nodes have priority if f and h is equal

  bestCostToState = {startKey:0}  # g is 0

  parentRelations = {startKey:(None,None)}  # (Parent , Move Used)

  totalNodesExpanded = 0
  tieBreakerCount = 1

  currentFinalLayer = initialH
  nodesInCurrentLayer = 0


  while frontier:  # while goal = false
    if resourceMonitor.shouldTerminateSearch():
      return {'Solved' :False , 'moves': [] , 'nodesExpanded': totalNodesExpanded , 'finalLayerNodes' : nodesInCurrentLayer , 'searchTime' : time.perf_counter() -searchStartTimer }  # Memory condition

    fcost,hcost,tieC,currentKey = heapq.heappop(frontier)  # node = lowest(f=g+h)

    if fcost != currentFinalLayer:  # track which f cost
      currentFinalLayer = fcost
      nodesInCurrentLayer = 0
    nodesInCurrentLayer += 1

    actualGCost = bestCostToState.get(currentKey,float('inf')) # skipping outdated entries
    if fcost - hcost > actualGCost:
      continue  # ignore old entries with worse path

    currentState = bytesToTuple(currentKey) # to process heurisitc

    if hcost==0:
      solutionMoves = []
      reconstruction = currentKey
      while parentRelations[reconstruction][0] is not None:
        parentKey,moveUsed = parentRelations[reconstruction]
        solutionMoves.append(moveUsed)
        reconstruction = parentKey
      solutionMoves.reverse()  #start to goal actions


      return {'Solved' :True , 'moves': solutionMoves , 'nodesExpanded': totalNodesExpanded , 'finalLayerNodes' : nodesInCurrentLayer , 'searchTime' : time.perf_counter() -searchStartTimer }  # Memory condition

    totalNodesExpanded += 1 # count each expanded node

    lastMoveUsed = parentRelations[currentKey][1]  # generating all possible successors

    for move in possibleMoves:  # push all children node
      if lastMoveUsed is not None and move == lastMoveUsed:  # avoid repating the same face immediatley
        continue
      nextState = rotateCounterClock(currentState,move)
      nextKey = tupleToBytes(nextState)


      newGcost = actualGCost + 1

      existingCost = bestCostToState.get(nextKey)  # if this path is better we push it

      if existingCost is None or newGcost < existingCost:
        bestCostToState[nextKey] = newGcost #update g
        parentRelations[nextKey] = (currentKey,move)  # parent pointer
        nextHuerisitc = HeuristicByCache(nextKey)
        nextfcost = newGcost + nextHuerisitc  #f' = g' + h'

        heapq.heappush(frontier, (nextfcost,nextHuerisitc,tieBreakerCount,nextKey))
        tieBreakerCount += 1

def applyCCWMoves(state:State,listOfMoves:list) -> State:
  for move in listOfMoves:
    state = rotateCounterClock(state,move[0])
  return state

def runTests(trailsPerK,minK,maxK):
  rm = ResourceMonitor()
  for k in range (minK,maxK+1):
    print(f"Running {trailsPerK} trials for k = {k}")
    trailsStats = []


    totalTime = 0
    totalNodes = 0
    totalLastLayer = 0
    TotalSolLength = 0
    SolvedCounter = 0

    for trialIndex in range (1,trailsPerK+1):
      startConfig = startingConfig()

      randomState, listOfMoves = CWRandomizer(startConfig,k)
      displayGUI(randomState)

      heuristicOfRandom = heuristic(randomState) # Call the heuristic function with the randomState
      print(f"The random state at trial {trialIndex}  and {k} random moves has a heurisitc of {heuristicOfRandom}") # Print the result

      startTimer = time.perf_counter()
      solution = aStarMethod(randomState,rm)
      timeEllapased = time.perf_counter() - startTimer

      solved = solution.get('Solved',False)
      moves = solution.get('moves',[])
      nodesExpanded = solution.get('nodesExpanded',0)
      finalLayerNodes = solution.get('finalLayerNodes',0)
      solLength = len(moves) if solved else 0

      # accumlate averages

      totalTime +=timeEllapased
      totalNodes += nodesExpanded
      totalLastLayer+= finalLayerNodes
      if solved:
        SolvedCounter+=1
        TotalSolLength += solLength

      #per trial
      print(f"Solved : {solved}")
      print(f"Nodex Expanded: {nodesExpanded}")
      print(f"Nodes on last layer: {finalLayerNodes}")
      if solved:
        print(f"Solution Length : {solLength}")
        print(f"Solution : {moves}")
        displayGUI(applyCCWMoves(randomState,moves))
      else:
        print("Unsolved")
      print(f"elapsed Time {timeEllapased}")

      #Running Averages

      averageTime = totalTime / trialIndex
      averageNodes = totalNodes / trialIndex
      averageLastLayer = totalLastLayer / trialIndex
      averageLength = TotalSolLength / SolvedCounter if SolvedCounter > 0 else 0

      print("Current Running Average")
      print(f"Average Time {averageTime}")
      print(f"Average Nodes {averageNodes}")
      print(f"Average Nodes on last layer {averageLastLayer}")
      print(f"Average Solution Length {averageLength}")
    #For Each K summary over all trials

    print(f" FULL Summary for k = {k}")
    print(f"Average Time {averageTime}")
    print(f"Average Nodes {averageNodes}")
    print(f"Average Nodes on last layer {averageLastLayer}")

def main():
    """
    Main function to run the Sudoku Cube solver.
    Modify parameters here to customize the test runs.
    """
    print("=" * 60)
    print("Sudoku Cube A* Solver")
    print("=" * 60)
    
    # Run tests with customizable parameters
    # Format: runTests(trials_per_k, min_k, max_k)
    # Example: runTests(5, 1, 10) runs 5 trials for k=1 through k=10
    
    runTests(1, 8, 15)  # Current default: 1 trial for k=6 through k=15

if __name__ == "__main__":
    main()